<a href="https://colab.research.google.com/github/sho-playground/machine-learning/blob/master/playground_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

NumPy Tutorial:
https://numpy.org/doc/stable/user/absolute_beginners.html

In [14]:
a = np.arange(6)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.shape

numpy.ndarray

In [5]:
a.dtype

dtype('int64')

In [8]:
b = np.zeros(2)
b.dtype

dtype('float64')

In [9]:
c = np.empty(2)
c

array([ 1.28822975e-231, -2.00389354e+000])

In [10]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7,8]])
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [11]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [12]:
# number of dimensions is also called rank
array_example.ndim

3

In [5]:
array_example.size

24

In [7]:
array_example.shape

(3, 2, 4)

In [13]:
np.random.randn(6, 4)

array([[-1.50390283, -0.545298  , -0.93369799, -0.70917717],
       [-1.58971048,  0.36769447, -0.71495543,  0.71327024],
       [-1.91404495, -0.82901474, -0.90429557,  1.83162265],
       [-0.71436569, -0.73633491,  0.7012713 , -0.04222754],
       [-2.05735933, -0.68221096, -1.13388903,  0.72864427],
       [-0.5567618 ,  1.00893755,  1.44639119,  0.37534921]])

In [12]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [13]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [5]:
b = np.reshape(a, newshape=(1, 6), order='C')
b
b.shape

(1, 6)

In [11]:
a2 = a[np.newaxis, :]
a2.shape
a2

array([[1, 2, 3, 4, 5, 6]])

In [5]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

# iterating over multidimensional arrays is done with respect to the first axis:
for row in c:
    print(row)

# with flat you can iterate over the elements
for element in c.flat:
    print(element)

[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]
0
1
2
10
12
13
100
101
102
110
112
113
